version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8080:8080"

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server